# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  name: 'CAMEO'
  demands:
    - Location -equals CAMEOCumulus

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'AVL Artifactory'
    cliInstallationRepo: 'cached-go-jfrog.bintray.com'

- task: PowerShell@2
  inputs:
    filePath: 'publish.ps1'
    arguments: -DestDir $(Build.ArtifactStagingDirectory)/dist

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'AVL Artifactory'
    fileSpec: |
     {
       "files": [
                  {
                    "pattern": "$(Build.ArtifactStagingDirectory)/dist/UpdateCameoDev.zip",
                    "target": "repo-snapshot/AVL/CAMEO/UpdateCameoDev/"
                  }
       ]
     }

